# Generated by Django 4.0.6 on 2022-09-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Books_Group_under',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_under_Name', models.CharField(blank=True, default='Null', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Books_Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(blank=True, default='Null', max_length=225)),
                ('ledger_opening_bal', models.IntegerField(blank=True, default='Null')),
                ('ledger_opening_bal_type', models.CharField(blank=True, default='Null', max_length=225)),
                ('group_under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.account_books_group_under')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_path', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('mailing_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('fax', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('formal_name', models.CharField(max_length=20)),
                ('fin_begin', models.DateField()),
                ('books_begin', models.DateField()),
                ('fin_end', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tally_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('group_under', models.CharField(blank=True, max_length=255, null=True)),
                ('nature', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_profit', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_ledger', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.companies')),
            ],
        ),
        migrations.CreateModel(
            name='tally_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('under', models.CharField(blank=True, max_length=255, null=True)),
                ('mname', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('bank_details', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_type', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_uin', models.CharField(blank=True, max_length=100, null=True)),
                ('set_alter_gstdetails', models.CharField(max_length=100, null=True)),
                ('opening_blnc', models.IntegerField(blank=True, null=True)),
                ('opening_blnc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('set_odl', models.CharField(blank=True, max_length=255, null=True)),
                ('ac_holder_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_no', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('SA_cheque_bk', models.CharField(blank=True, max_length=20, null=True)),
                ('Echeque_p', models.CharField(blank=True, max_length=20, null=True)),
                ('SA_chequeP_con', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_ledger', models.CharField(blank=True, max_length=100, null=True)),
                ('rounding_method', models.CharField(blank=True, max_length=100, null=True)),
                ('rounding_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('type_duty_tax', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_type', models.CharField(blank=True, max_length=100, null=True)),
                ('valuation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rate_per_unit', models.IntegerField(blank=True, default=None, null=True)),
                ('percentage_of_calcution', models.CharField(blank=True, max_length=100, null=True)),
                ('rond_method', models.CharField(blank=True, max_length=100, null=True)),
                ('rond_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('gst_applicable', models.CharField(blank=True, max_length=100, null=True)),
                ('setalter_gstdetails', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('assessable_value', models.CharField(blank=True, max_length=100, null=True)),
                ('appropriate_to', models.CharField(blank=True, max_length=100, null=True)),
                ('method_of_calculation', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_billbybill', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_period', models.CharField(blank=True, max_length=100, null=True)),
                ('creditdays_voucher', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.companies')),
                ('grp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.tally_group')),
            ],
        ),
        migrations.CreateModel(
            name='cash_bank_books_TotalClosing_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Closing_balance', models.IntegerField(blank=True, default='', null=True)),
                ('type', models.CharField(max_length=225)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.account_books_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='cash_bank_books_Leger_Month_closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closing_balance', models.IntegerField(blank=True, default='', null=True)),
                ('type', models.CharField(max_length=225)),
                ('debit', models.IntegerField(blank=True, default='', null=True)),
                ('credit', models.IntegerField(blank=True, default='', null=True)),
                ('Ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.account_books_ledger')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.months')),
            ],
        ),
        migrations.CreateModel(
            name='cash_bank_books_Group_Under_closing_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_closing_balance_debit', models.IntegerField(blank=True, default='', null=True)),
                ('total_closing_balance_credit', models.IntegerField(blank=True, default='', null=True)),
                ('group_under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally_app.account_books_group_under')),
            ],
        ),
        migrations.CreateModel(
            name='Account_books_Ledger_Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Particualrs', models.CharField(max_length=225)),
                ('Vch_Type', models.CharField(max_length=225)),
                ('Vch_No', models.CharField(max_length=225)),
                ('Debit', models.IntegerField(blank=True, default='', null=True)),
                ('Credit', models.IntegerField(blank=True, default='', null=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.account_books_ledger')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.months')),
            ],
        ),
    ]
