# Generated by Django 4.0.6 on 2022-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0002_alter_ledger_voucher_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_voucher',
            name='Credit',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
