# Generated by Django 4.0.6 on 2022-08-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0004_alter_ledger_ledger_opening_bal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Closing_balance', models.IntegerField()),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tally_app.ledger')),
            ],
        ),
    ]
