# Generated by Django 4.0.6 on 2022-08-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0005_closing_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Under_closing_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_closing_balance', models.IntegerField()),
                ('group_under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tally_app.group_under')),
            ],
        ),
    ]
