# Generated by Django 4.0.6 on 2022-08-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0006_group_under_closing_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_under_closing_balance',
            old_name='total_closing_balance',
            new_name='total_closing_balance_credit',
        ),
        migrations.AddField(
            model_name='group_under_closing_balance',
            name='total_closing_balance_debit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
