# Generated by Django 4.0.6 on 2022-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0007_rename_total_closing_balance_group_under_closing_balance_total_closing_balance_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_opening_bal_type',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
