# Generated by Django 4.0.6 on 2022-08-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0009_rename_ledger_type_ledger_ledger_ob_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='ledger_ob_type',
            new_name='ledger_type',
        ),
    ]
