# Generated by Django 4.0.6 on 2022-08-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0010_rename_ledger_ob_type_ledger_ledger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing_balance',
            name='Closing_balance',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='group_under_closing_balance',
            name='total_closing_balance_credit',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='group_under_closing_balance',
            name='total_closing_balance_debit',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
