# Generated by Django 4.0.6 on 2022-09-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tally_app', '0012_ledgermonths_leger_month_closing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ledger_Voucher',
            new_name='Account_books_Ledger_Voucher',
        ),
        migrations.RenameModel(
            old_name='Group_Under_closing_balance',
            new_name='cash_bank_books_Group_Under_closing_balance',
        ),
        migrations.RenameModel(
            old_name='Leger_Month_closing',
            new_name='cash_bank_books_Leger_Month_closing',
        ),
        migrations.RenameModel(
            old_name='TotalClosing_balance',
            new_name='cash_bank_books_TotalClosing_balance',
        ),
        migrations.RenameModel(
            old_name='LedgerMonths',
            new_name='Months',
        ),
    ]
